[package]
authors = ["Port Finance Maintainers <maintainers@solana.foundation>"]
description = "Port Finance Lending CLI"
edition = "2021"
homepage = ""
license = "Apache-2.0"
name = "port-lending-cli"
repository = "https://github.com/port-finance"
version = "0.1.0"

[dependencies]
clap = "2.33.3"
solana-clap-utils = "1.18.26"
solana-cli-config = "1.18.26"
solana-remote-wallet = "1.18.26"
solana-client = "1.18.26"
solana-logger = "1.18.26"
solana-sdk = "1.18.26"
solana-program = "1.18.26"
port-finance-variable-rate-lending = { path = "../program", features = ["no-entrypoint"] }
spl-token = { version = "4.0", features = ["no-entrypoint"] }

[[bin]]
name = "port-lending-cli"
path = "src/main.rs"